-- Integrated schema for boatrace-ai-free
-- Generated at: 2026-05-18T00:44:11.118690+00:00
-- Generated by: scripts/export_integrated_schema.py

PRAGMA foreign_keys = ON;

-- table: alert_events
CREATE TABLE alert_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  prediction_run_id INTEGER,
  race_id INTEGER,

  level TEXT NOT NULL,
  alert_type TEXT NOT NULL,
  message TEXT NOT NULL,

  details_json TEXT,

  occurred_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TEXT,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (prediction_run_id) REFERENCES prediction_runs(id) ON DELETE SET NULL,
  FOREIGN KEY (race_id) REFERENCES races(id) ON DELETE SET NULL,

  CHECK (level IN ('warning', 'danger', 'info')),
  CHECK (
    alert_type IN (
      'ticket_count',
      'total_amount',
      'update_delay',
      'update_unknown',
      'missing_exhibition_time',
      'missing_exhibition_st',
      'missing_final_odds',
      'data_fetch_error',
      'prediction_error',
      'other'
    )
  )
);

-- table: export_logs
CREATE TABLE export_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  prediction_run_id INTEGER,

  export_type TEXT NOT NULL DEFAULT 'prediction_json',
  output_path TEXT NOT NULL,
  exported_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  status TEXT NOT NULL DEFAULT 'completed',
  message TEXT,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (prediction_run_id) REFERENCES prediction_runs(id) ON DELETE SET NULL,

  CHECK (
    export_type IN (
      'prediction_json',
      'alert_settings_json',
      'report_json',
      'csv',
      'other'
    )
  ),
  CHECK (
    status IN (
      'completed',
      'failed'
    )
  )
);

-- table: odds_snapshots
CREATE TABLE odds_snapshots (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  race_id INTEGER NOT NULL,

  bet_type TEXT NOT NULL,
  combination TEXT NOT NULL,
  odds REAL,
  popularity INTEGER,

  captured_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source TEXT,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (race_id) REFERENCES races(id) ON DELETE CASCADE,

  CHECK (
    bet_type IN (
      'tansho',
      'fukusho',
      '2rentan',
      '2renfuku',
      '3rentan',
      '3renfuku',
      'kakuren',
      'unknown'
    )
  )
);

-- table: prediction_runs
CREATE TABLE prediction_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  run_key TEXT NOT NULL UNIQUE,

  target_date TEXT NOT NULL,
  executed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  model_name TEXT NOT NULL,
  model_version TEXT,
  model_params_json TEXT,

  data_version TEXT,
  source_summary_json TEXT,

  status TEXT NOT NULL DEFAULT 'completed',
  memo TEXT,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CHECK (
    status IN (
      'created',
      'running',
      'completed',
      'failed',
      'cancelled'
    )
  )
);

-- table: prediction_tickets
CREATE TABLE prediction_tickets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  prediction_id INTEGER NOT NULL,

  bet_type TEXT NOT NULL DEFAULT '3rentan',
  combination TEXT NOT NULL,

  amount INTEGER NOT NULL DEFAULT 0,

  estimated_probability REAL,
  expected_odds REAL,
  expected_value REAL,

  rank_no INTEGER,
  confidence REAL,
  reason TEXT,

  -- Result fields, updated after race result is known
  is_hit INTEGER,
  payout_amount INTEGER DEFAULT 0,
  profit_amount INTEGER,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, probability REAL DEFAULT 0.0, odds REAL DEFAULT 0.0, rank INTEGER DEFAULT 0, memo TEXT, payout INTEGER DEFAULT 0, profit INTEGER DEFAULT 0,

  FOREIGN KEY (prediction_id) REFERENCES predictions(id) ON DELETE CASCADE,

  CHECK (amount >= 0),
  CHECK (is_hit IS NULL OR is_hit IN (0, 1)),
  CHECK (
    bet_type IN (
      'tansho',
      'fukusho',
      '2rentan',
      '2renfuku',
      '3rentan',
      '3renfuku',
      'kakuren',
      'unknown'
    )
  )
);

-- table: predictions
CREATE TABLE predictions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  prediction_run_id INTEGER NOT NULL,
  race_id INTEGER NOT NULL,

  -- Main prediction summary
  favorite_boat_no INTEGER,
  rival_boat_no INTEGER,
  darkhorse_boat_no INTEGER,

  confidence REAL,
  expected_value REAL,
  recommended_total_amount INTEGER DEFAULT 0,

  -- Flexible details
  prediction_summary TEXT,
  features_json TEXT,
  scores_json TEXT,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (prediction_run_id) REFERENCES prediction_runs(id) ON DELETE CASCADE,
  FOREIGN KEY (race_id) REFERENCES races(id) ON DELETE CASCADE,

  UNIQUE (prediction_run_id, race_id),

  CHECK (favorite_boat_no IS NULL OR favorite_boat_no BETWEEN 1 AND 6),
  CHECK (rival_boat_no IS NULL OR rival_boat_no BETWEEN 1 AND 6),
  CHECK (darkhorse_boat_no IS NULL OR darkhorse_boat_no BETWEEN 1 AND 6)
);

-- table: race_entries
CREATE TABLE race_entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  race_id INTEGER NOT NULL,
  racer_id INTEGER NOT NULL,

  frame_no INTEGER NOT NULL,
  boat_no INTEGER NOT NULL,

  motor_no TEXT,
  boat_number TEXT,

  -- Pre-race stats
  national_win_rate REAL,
  national_2rentai_rate REAL,
  national_3rentai_rate REAL,
  local_win_rate REAL,
  local_2rentai_rate REAL,
  local_3rentai_rate REAL,

  motor_2rentai_rate REAL,
  motor_3rentai_rate REAL,
  boat_2rentai_rate REAL,
  boat_3rentai_rate REAL,

  -- Exhibition data
  exhibition_time REAL,
  exhibition_st REAL,
  tilt REAL,
  entry_course INTEGER,

  -- Start / result-related fields can be updated after race
  start_timing REAL,
  finish_order INTEGER,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, st_course INTEGER, st_timing REAL,

  FOREIGN KEY (race_id) REFERENCES races(id) ON DELETE CASCADE,
  FOREIGN KEY (racer_id) REFERENCES racers(id),

  UNIQUE (race_id, frame_no),
  UNIQUE (race_id, racer_id),

  CHECK (frame_no BETWEEN 1 AND 6),
  CHECK (boat_no BETWEEN 1 AND 6),
  CHECK (entry_course IS NULL OR entry_course BETWEEN 1 AND 6),
  CHECK (finish_order IS NULL OR finish_order BETWEEN 1 AND 6)
);

-- table: race_results
CREATE TABLE race_results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  race_id INTEGER NOT NULL UNIQUE,

  result_status TEXT NOT NULL DEFAULT 'official',

  first_boat_no INTEGER,
  second_boat_no INTEGER,
  third_boat_no INTEGER,

  winning_trick TEXT,

  -- Start accident / cancellation info
  has_flying INTEGER NOT NULL DEFAULT 0,
  has_late INTEGER NOT NULL DEFAULT 0,
  cancellation_json TEXT,

  -- Payouts in JSON for flexible handling
  payouts_json TEXT,

  -- Frequently used payout fields
  trifecta_combination TEXT,
  trifecta_payout INTEGER,
  trifecta_popularity INTEGER,

  exacta_combination TEXT,
  exacta_payout INTEGER,

  quinella_combination TEXT,
  quinella_payout INTEGER,

  finalized_at TEXT,
  source_url TEXT,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (race_id) REFERENCES races(id) ON DELETE CASCADE,

  CHECK (first_boat_no IS NULL OR first_boat_no BETWEEN 1 AND 6),
  CHECK (second_boat_no IS NULL OR second_boat_no BETWEEN 1 AND 6),
  CHECK (third_boat_no IS NULL OR third_boat_no BETWEEN 1 AND 6),
  CHECK (has_flying IN (0, 1)),
  CHECK (has_late IN (0, 1))
);

-- table: racers
CREATE TABLE racers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  racer_registration_no TEXT NOT NULL UNIQUE,
  racer_name TEXT NOT NULL,
  racer_name_kana TEXT,

  branch TEXT,
  birth_prefecture TEXT,
  class_name TEXT,

  -- Current stats / latest snapshot style fields
  national_win_rate REAL,
  national_2rentai_rate REAL,
  national_3rentai_rate REAL,
  local_win_rate REAL,
  local_2rentai_rate REAL,
  local_3rentai_rate REAL,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
, registration_no TEXT, racer_class TEXT, age INTEGER, weight REAL);

-- table: races
CREATE TABLE races (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  -- Natural identifiers
  race_date TEXT NOT NULL,
  venue_id INTEGER NOT NULL,
  race_no INTEGER NOT NULL,

  -- Race information
  race_name TEXT,
  grade TEXT,
  distance_m INTEGER DEFAULT 1800,
  deadline_at TEXT,
  start_at TEXT,

  -- Conditions
  weather TEXT,
  wind_direction TEXT,
  wind_speed_m REAL,
  wave_height_cm REAL,
  temperature_c REAL,
  water_temperature_c REAL,
  water_line TEXT,
  is_stabilizer_used INTEGER NOT NULL DEFAULT 0,
  is_fixed_entry INTEGER NOT NULL DEFAULT 0,

  -- Status
  status TEXT NOT NULL DEFAULT 'scheduled',
  source_url TEXT,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, distance INTEGER, start_time TEXT, wind_speed REAL, water_temperature REAL, wave_height INTEGER,

  FOREIGN KEY (venue_id) REFERENCES venues(id),

  UNIQUE (race_date, venue_id, race_no),

  CHECK (race_no BETWEEN 1 AND 12),
  CHECK (is_stabilizer_used IN (0, 1)),
  CHECK (is_fixed_entry IN (0, 1))
);

-- table: venues
CREATE TABLE venues (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  venue_code TEXT NOT NULL UNIQUE,
  venue_name TEXT NOT NULL,
  venue_name_kana TEXT,
  region TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- index: idx_alert_events_alert_type
CREATE INDEX idx_alert_events_alert_type
  ON alert_events (alert_type);

-- index: idx_alert_events_level
CREATE INDEX idx_alert_events_level
  ON alert_events (level);

-- index: idx_alert_events_occurred_at
CREATE INDEX idx_alert_events_occurred_at
  ON alert_events (occurred_at);

-- index: idx_alert_events_prediction_run_id
CREATE INDEX idx_alert_events_prediction_run_id
  ON alert_events (prediction_run_id);

-- index: idx_alert_events_race_id
CREATE INDEX idx_alert_events_race_id
  ON alert_events (race_id);

-- index: idx_export_logs_exported_at
CREATE INDEX idx_export_logs_exported_at
  ON export_logs (exported_at);

-- index: idx_export_logs_prediction_run_id
CREATE INDEX idx_export_logs_prediction_run_id
  ON export_logs (prediction_run_id);

-- index: idx_odds_snapshots_captured_at
CREATE INDEX idx_odds_snapshots_captured_at
  ON odds_snapshots (captured_at);

-- index: idx_odds_snapshots_race_bet_combo
CREATE INDEX idx_odds_snapshots_race_bet_combo
  ON odds_snapshots (race_id, bet_type, combination);

-- index: idx_odds_snapshots_race_id
CREATE INDEX idx_odds_snapshots_race_id
  ON odds_snapshots (race_id);

-- index: idx_prediction_runs_executed_at
CREATE INDEX idx_prediction_runs_executed_at
  ON prediction_runs (executed_at);

-- index: idx_prediction_runs_status
CREATE INDEX idx_prediction_runs_status
  ON prediction_runs (status);

-- index: idx_prediction_runs_target_date
CREATE INDEX idx_prediction_runs_target_date
  ON prediction_runs (target_date);

-- index: idx_prediction_tickets_bet_type
CREATE INDEX idx_prediction_tickets_bet_type
  ON prediction_tickets (bet_type);

-- index: idx_prediction_tickets_is_hit
CREATE INDEX idx_prediction_tickets_is_hit
  ON prediction_tickets (is_hit);

-- index: idx_prediction_tickets_prediction_id
CREATE INDEX idx_prediction_tickets_prediction_id
  ON prediction_tickets (prediction_id);

-- index: idx_predictions_confidence
CREATE INDEX idx_predictions_confidence
  ON predictions (confidence);

-- index: idx_predictions_race_id
CREATE INDEX idx_predictions_race_id
  ON predictions (race_id);

-- index: idx_predictions_run_id
CREATE INDEX idx_predictions_run_id
  ON predictions (prediction_run_id);

-- index: idx_race_entries_frame
CREATE INDEX idx_race_entries_frame
  ON race_entries (race_id, frame_no);

-- index: idx_race_entries_race_id
CREATE INDEX idx_race_entries_race_id
  ON race_entries (race_id);

-- index: idx_race_entries_racer_id
CREATE INDEX idx_race_entries_racer_id
  ON race_entries (racer_id);

-- index: idx_race_results_finalized_at
CREATE INDEX idx_race_results_finalized_at
  ON race_results (finalized_at);

-- index: idx_race_results_race_id
CREATE INDEX idx_race_results_race_id
  ON race_results (race_id);

-- index: idx_race_results_trifecta
CREATE INDEX idx_race_results_trifecta
  ON race_results (trifecta_combination);

-- index: idx_racers_class_name
CREATE INDEX idx_racers_class_name
  ON racers (class_name);

-- index: idx_racers_registration_no
CREATE INDEX idx_racers_registration_no
  ON racers (racer_registration_no);

-- index: idx_races_race_date
CREATE INDEX idx_races_race_date
  ON races (race_date);

-- index: idx_races_status
CREATE INDEX idx_races_status
  ON races (status);

-- index: idx_races_venue_date
CREATE INDEX idx_races_venue_date
  ON races (venue_id, race_date);

-- index: idx_venues_venue_code
CREATE INDEX idx_venues_venue_code
  ON venues (venue_code);

-- index: ux_racers_racer_registration_no
CREATE UNIQUE INDEX ux_racers_racer_registration_no
            ON racers(racer_registration_no);

-- index: ux_racers_registration_no
CREATE UNIQUE INDEX ux_racers_registration_no
            ON racers(registration_no);

-- index: ux_venues_venue_code
CREATE UNIQUE INDEX ux_venues_venue_code
            ON venues(venue_code);

-- view: v_prediction_run_summary
CREATE VIEW v_prediction_run_summary AS
SELECT
  pr.id AS prediction_run_id,
  pr.run_key,
  pr.target_date,
  pr.executed_at,
  pr.model_name,
  pr.model_version,
  COUNT(DISTINCT p.race_id) AS race_count,
  COUNT(t.id) AS ticket_count,
  COALESCE(SUM(t.amount), 0) AS total_amount,
  COALESCE(SUM(t.payout_amount), 0) AS total_payout,
  COALESCE(SUM(t.payout_amount), 0) - COALESCE(SUM(t.amount), 0) AS total_profit,
  CASE
    WHEN COALESCE(SUM(t.amount), 0) = 0 THEN NULL
    ELSE ROUND(COALESCE(SUM(t.payout_amount), 0) * 100.0 / SUM(t.amount), 2)
  END AS return_rate_percent,
  CASE
    WHEN COUNT(t.id) = 0 THEN NULL
    ELSE ROUND(SUM(CASE WHEN t.is_hit = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(t.id), 2)
  END AS hit_rate_percent
FROM prediction_runs pr
LEFT JOIN predictions p
  ON p.prediction_run_id = pr.id
LEFT JOIN prediction_tickets t
  ON t.prediction_id = p.id
GROUP BY
  pr.id,
  pr.run_key,
  pr.target_date,
  pr.executed_at,
  pr.model_name,
  pr.model_version;

-- view: v_prediction_ticket_results
CREATE VIEW v_prediction_ticket_results AS
SELECT
  pr.id AS prediction_run_id,
  pr.run_key,
  pr.target_date,
  pr.model_name,
  pr.model_version,
  p.id AS prediction_id,
  p.race_id,
  t.id AS ticket_id,
  t.bet_type,
  t.combination,
  t.amount,
  t.estimated_probability,
  t.expected_odds,
  t.expected_value,
  t.is_hit,
  t.payout_amount,
  t.profit_amount
FROM prediction_runs pr
JOIN predictions p
  ON p.prediction_run_id = pr.id
JOIN prediction_tickets t
  ON t.prediction_id = p.id;

-- view: v_race_overview
CREATE VIEW v_race_overview AS
SELECT
  r.id AS race_id,
  r.race_date,
  v.venue_code,
  v.venue_name,
  r.race_no,
  r.race_name,
  r.grade,
  r.deadline_at,
  r.start_at,
  r.status,
  r.weather,
  r.wind_speed_m,
  r.wave_height_cm,
  r.temperature_c,
  r.water_temperature_c
FROM races r
JOIN venues v
  ON r.venue_id = v.id;


-- STEP109: prediction run history
CREATE TABLE IF NOT EXISTS prediction_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_key TEXT NOT NULL UNIQUE,
    model_name TEXT NOT NULL,
    model_version TEXT NOT NULL,
    target_date TEXT NOT NULL,
    started_at TEXT,
    finished_at TEXT,
    status TEXT NOT NULL DEFAULT 'completed',
    race_count INTEGER NOT NULL DEFAULT 0,
    recommendation_count INTEGER NOT NULL DEFAULT 0,
    high_ev_count INTEGER NOT NULL DEFAULT 0,
    alert_count INTEGER NOT NULL DEFAULT 0,
    quality_score REAL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_prediction_runs_target_date ON prediction_runs(target_date);
CREATE INDEX IF NOT EXISTS idx_prediction_runs_model ON prediction_runs(model_name, model_version);
CREATE INDEX IF NOT EXISTS idx_prediction_runs_status ON prediction_runs(status);

-- STEP120: race results and payouts
CREATE TABLE IF NOT EXISTS race_results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    race_id INTEGER NOT NULL,
    result_status TEXT NOT NULL DEFAULT 'official' CHECK (result_status IN ('pending', 'official', 'cancelled', 'no_contest')),
    first_place INTEGER,
    second_place INTEGER,
    third_place INTEGER,
    winning_method TEXT,
    decided_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT,
    UNIQUE(race_id),
    FOREIGN KEY (race_id) REFERENCES races(id)
);

CREATE INDEX IF NOT EXISTS idx_race_results_race_id ON race_results(race_id);
CREATE INDEX IF NOT EXISTS idx_race_results_status ON race_results(result_status);

CREATE TABLE IF NOT EXISTS payouts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    race_id INTEGER NOT NULL,
    bet_type TEXT NOT NULL CHECK (bet_type IN ('trifecta', 'trio', 'exacta', 'quinella', 'wide', 'win', 'place')),
    ticket TEXT NOT NULL,
    payout_yen INTEGER NOT NULL DEFAULT 0 CHECK (payout_yen >= 0),
    popularity INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(race_id, bet_type, ticket),
    FOREIGN KEY (race_id) REFERENCES races(id)
);

CREATE INDEX IF NOT EXISTS idx_payouts_race_id ON payouts(race_id);
CREATE INDEX IF NOT EXISTS idx_payouts_bet_type ON payouts(bet_type);
CREATE INDEX IF NOT EXISTS idx_payouts_ticket ON payouts(ticket);
