#!/usr/bin/env python3
import sqlite3
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


DB_PATH = Path("db/boatrace.sqlite3")
SCHEMA_PATH = Path("db/schema.sql")
PYTHON = sys.executable


def run(command: list[str]) -> None:
    print("")
    print("=" * 80)
    print("RUN:", " ".join(command))
    print("=" * 80)

    result = subprocess.run(command)
    if result.returncode != 0:
        raise SystemExit(f"Command failed: {' '.join(command)}")


def fetch_schema_objects(conn: sqlite3.Connection):
    rows = conn.execute(
        """
        SELECT type, name, tbl_name, sql
        FROM sqlite_master
        WHERE sql IS NOT NULL
          AND name NOT LIKE 'sqlite_%'
        ORDER BY
          CASE type
            WHEN 'table' THEN 1
            WHEN 'index' THEN 2
            WHEN 'trigger' THEN 3
            WHEN 'view' THEN 4
            ELSE 9
          END,
          name
        """
    ).fetchall()
    return rows


def main() -> None:
    print("STEP 104 export integrated schema")

    # 既存の build_database.py を使って、パッチ適用済みの完成DBを作る
    run([PYTHON, "scripts/build_database.py", "--reset"])

    if not DB_PATH.exists():
        raise SystemExit(f"Database not found: {DB_PATH}")

    conn = sqlite3.connect(DB_PATH)
    rows = fetch_schema_objects(conn)

    if not rows:
        raise SystemExit("No schema objects found")

    lines = []
    lines.append("-- Integrated schema for boatrace-ai-free")
    lines.append(f"-- Generated at: {datetime.now(timezone.utc).isoformat()}")
    lines.append("-- Generated by: scripts/export_integrated_schema.py")
    lines.append("")
    lines.append("PRAGMA foreign_keys = ON;")
    lines.append("")

    for obj_type, name, tbl_name, sql in rows:
        lines.append(f"-- {obj_type}: {name}")
        sql = sql.strip().rstrip(";")
        lines.append(sql + ";")
        lines.append("")

    SCHEMA_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print("")
    print(f"Wrote integrated schema: {SCHEMA_PATH}")
    print(f"Schema objects exported: {len(rows)}")

    conn.close()

    print("STEP 104 EXPORT SCHEMA: OK")


if __name__ == "__main__":
    main()
