name: Make Prediction JSON

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  make-prediction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run prediction script
        run: python src/make_prediction.py

      - name: Commit and push prediction.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs/prediction.json
          git commit -m "Update prediction.json" || echo "No changes to commit"
          git push
